# Generated automatically from Makefile.config.in by configure.
##
## Makefile.config
##
## This file is part of ht://Dig
##
include $(top_builddir)/CONFIG

#
# You should not have to modify anything below this point.
#

SHELL=                  /bin/sh

#
# Locations of programs
#
CXX=		c++
CC=		gcc
RANLIB=		ranlib
MAKEDEPEND=	/var/www/test/testme/my_htdig/htdig-3.1.6/makedp
FIND=		/usr/bin/find
AR=		/usr/bin/ar
PDF_PARSER=	/usr/local/bin/acroread
SENDMAIL=	/usr/sbin/sendmail

DEFINES=	-DDEFAULT_CONFIG_FILE=\"$(DEFAULT_CONFIG_FILE)\"
LIBDIRS=	-L../htlib -L../htcommon -L../db/dist -L/usr/lib
INCS=		-I$(top_srcdir)/htlib -I$(top_srcdir)/htcommon \
		-I../db/dist -I../include
HTLIBS=		../htcommon/libcommon.a \
		../htlib/libht.a \
		../db/dist/libdb.a
LIBS=		$(HTLIBS) -lz 

DIST=		htdig-3.1.6
DISTDIR=	$(top_srcdir)/../$(DIST)

CFLAGS=		
CPPFLAGS=	
CXXFLAGS=	-g -O2
ALL_CFLAGS=	$(LOCAL_DEFINES) $(DEFINES) $(INCS) $(CFLAGS)
ALL_CXXFLAGS=	$(LOCAL_DEFINES) $(DEFINES) $(INCS) $(CXXFLAGS)
LDFLAGS=	 $(LIBDIRS)

.SUFFIXES: .cc
.cc.o:
	$(CXX) -c $(ALL_CXXFLAGS) $<

.c.o:
	$(CC) -c $(CPPFLAGS) $(ALL_CFLAGS) $<

